
import type { Metadata } from "next";
import "./globals.css";
import { PostProvider } from "@/lib/postContext";
import AppShell from "@/components/Layout/AppShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="flex flex-col h-screen bg-gray-50">
        <PostProvider>
          <AppShell>{children}</AppShell>
        </PostProvider>

      </body>
    </html>
  );
}
