import type { Metadata } from "next";
import "./globals.css";
import { PostProvider } from "@/lib/postContext";
import AppShell from "@/components/Layout/AppShell";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import { ChatProvider } from "@/context/ChatContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="flex flex-col  bg-gray-50 h-[100dvh]">
        <AuthProvider>
          <Toaster richColors position="top-center" />
          <PostProvider>
            <ChatProvider>
              <AppShell>{children}</AppShell>
            </ChatProvider>
          </PostProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
